WebExcelDownload/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebExcelDownload.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload
        public ActionResult Index()
        {
            var items = GetFiles();
            return View(items);
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            //aqui empieza el metodo de guardado, hacemos una sobrecarga con el metodo Index
            if (file == null && file.ContentLength<0)
            {
                ViewBag.Message = "No haz metido ningun archivo";
                
            }
            try
            {
                string path = Path.Combine(Server.MapPath("~/Archives"),
                    Path.GetFileName(file.FileName));

                file.SaveAs(path);
                ViewBag.Message = "Archivo se ha subido exitosamente!";
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error: "+ex.Message;
                
            }
            var items = GetFiles();
            return View(items);
        }

        public FileResult Download(string fileName)
        {
            var fileVirtualPath = "~/Archives/" + fileName;
            return File(fileVirtualPath,"application/force- download",Path.GetFileName(fileVirtualPath));
        }
        private List<string> GetFiles()
        {
            List<string> files = new List<string>();
            var dir = new System.IO.DirectoryInfo(Server.MapPath("~/Archives"));
            System.IO.FileInfo[] fileNames = dir.GetFiles("*.*"); //me devuelve todo tipo de archivos
            foreach (var file in fileNames)
            {
                files.Add(file.Name);
            }
            return files;
        }


     
    }
}

WebExcelDownload/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebExcelDownload.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult GuardarExcel(HttpPostedFileBase archivo)
        {
            Session["archivo"]= archivo.FileName;
            return null;
        }

        public ActionResult DevolverExcel()
        {
            String pathFile = Session["archivo"].ToString();
            return null;
        }
    }
}

WebExcelDownload/Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Subir Archivo Excel</h2>
@model List<string>
@using (Html.BeginForm("Index", "FileUpload",
    FormMethod.Post,
    new { enctype = "multipart/form-data" }))
            {
            <div class="container form-group table-bordered " >
                <label for="file">Subri archivo:</label>
                <input class="input-lg" type="file" name="file" id="file" />
                <br />

                <input class="input-lg" type="submit" value="Subir Archivo" />
                <br />
                @ViewBag.Message @*estado mensaje de carga*@
                <br />
            </div>
                
           
<h2>Descargar Archivo Excel</h2>
<div class="container table-bordered" >
    <table>
        <tr>
            <th>File name</th>
            <th>Enlace</th>
        </tr>
        @for (int i = 0; i <= Model.Count - 1 ; i++)
        {
            <tr>
                <td>@Model[i].ToString()</td>
                <td>@Html.ActionLink("Descargar","Download",new { FileName = @Model[i].ToString() })</td>
            </tr>
        }
    </table>
</div>

}

WebExcelDownload/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebExcelDownload/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebExcelDownload/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h1>Index Home</h1>

WebExcelDownload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Subir/descarga archivo", "Index", "FileUpload")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>